name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    - uses: pdm-project/setup-pdm@v4
      name: Setup PDM
      with:
        python-version: ${{ inputs.python-version }}
        cache: true

    - run: pdm sync -G:all
      shell: bash
